name: Firebase Deploy

on:
  push:
    branches:
      - main  # Workflow akan dijalankan saat ada push ke branch main

jobs:
  deploy:
    runs-on: ubuntu-latest  # Menjalankan di lingkungan Ubuntu

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2  # Mengambil kode dari repository

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'  # Menentukan versi Node.js yang digunakan

    - name: Install dependencies
      run: |
        npm install  # Menginstal dependencies

    - name: Build application
      run: |
        npm run build  # Membangun aplikasi (pastikan Anda sudah punya script build di package.json)

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v0
      with:
        project_id: ${{ secrets.FIREBASE_PROJECT_ID }}  # ID Proyek Firebase (dari Secrets)
        service_account_key: ${{ secrets.GCP_CREDENTIALS }}  # JSON key Firebase Project (dari Secrets)

    - name: Install Firebase CLI
      run: |
        npm install -g firebase-tools  # Menginstal Firebase CLI

    - name: Firebase Deploy
      run: |
        firebase deploy --only hosting --token ${{ secrets.FIREBASE_AUTH_TOKEN }}  # Deploy aplikasi ke Firebase Hosting

    - name: Cache node modules
      uses: actions/cache@v3
      with:
        path: node_modules  # Menyimpan cache untuk node_modules agar lebih cepat pada build berikutnya
        key: ${{ runner.os }}-node-modules-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-modules-
